version: '3'
volumes:
  postgresql_data:
    driver: local      
    name: postgresql-volume

services:
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "8088:8080"
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: "true"
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgresql           
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - postgresql_data:/bitnami/postgresql
